[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_mixer = "AQW933TrdFxE5q7982Vb57crHjZe3B7EZaHotdXnaQYQ"

[programs.devnet]
solana_mixer = "AQW933TrdFxE5q7982Vb57crHjZe3B7EZaHotdXnaQYQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
